name: 1.a. Build & Test Project
on:
  pull_request:
    types: [opened, synchronize, reopened]
  workflow_dispatch:

env:
  GHCR_REGISTRY: ghcr.io
  DOCKER_REPOSITORY: openldes/ldesserver
  SONAR_ORGANIZATION: ${{ vars.SONAR_ORGANIZATION }}
  SONAR_PROJECT_KEY: ${{ vars.SONAR_PROJECT_KEY }}
  ANALYSE_PACKAGE: ${{ vars.ANALYSE_PACKAGE }}
  JAVA_DISTRIBUTION: ${{ vars.JAVA_DISTRIBUTION }}
  JAVA_VERSION: ${{ vars.JAVA_VERSION }}

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0  # Shallow clones should be disabled for a better relevancy of analysis
      - name: Set up Java
        uses: actions/setup-java@v5
        with:
          distribution: ${{ env.JAVA_DISTRIBUTION }}
          java-version: ${{ env.JAVA_VERSION }}
      - name: Cache SonarCloud packages
        uses: actions/cache@v5
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar
      - name: Cache Maven packages
        uses: actions/cache@v5
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
      - name: Build and analyze
        if: ${{ github.actor != 'dependabot[bot]' && !github.event.pull_request.head.repo.fork && env.ANALYSE_PACKAGE == true }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: mvn -B verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar -Dsonar.projectKey=${{ env.SONAR_PROJECT_KEY }} -Dsonar.organization=${{ env.SONAR_ORGANIZATION }} -Pcoverage
      - name: Build and verify # https://portal.productboard.com/sonarsource/1-sonarcloud/c/50-sonarcloud-analyzes-external-pull-request
        if: ${{ github.actor == 'dependabot[bot]' || github.event.pull_request.head.repo.fork || env.ANALYSE_PACKAGE != true }}
        run: mvn -B verify
      - name: Upload JARs
        uses: actions/upload-artifact@v6
        with:
          name: artifacts
          path: |
            **/*with-dependencies.jar
            **/*application.jar
  build-and-scan-image:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      contents: read          # Required to checkout and read repo files
      security-events: write  # Required to upload SARIF files to Security tab
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v4
      - name: Download JARs
        uses: actions/download-artifact@v8
        with:
          name: artifacts
          path: .github
      - name: Define docker variables
        run: |
          VERSION=$(mvn help:evaluate -Dexpression="project.version" -q -DforceStdout)
          echo "IMAGE_TAG=${VERSION}-$(date +'%Y%m%d%H%M%S')" >> $GITHUB_ENV
          echo "IMAGE=${{ env.GHCR_REGISTRY }}/${{ github.repository }}" >> $GITHUB_ENV
      - name: Build and push Docker image
        uses: docker/build-push-action@v7
        with:
          context: .github
          push: false
          load: true
          outputs: type=docker,dest=./ldesserver-${{ env.IMAGE_TAG }}.tar
          tags: '${{ env.GHCR_REGISTRY }}/${{ env.DOCKER_REPOSITORY }}:${{ env.IMAGE_TAG }}'
      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@v0.36.0
        with:
          input: ./ldesserver-${{ env.IMAGE_TAG }}.tar
          format: 'sarif'
          output: 'trivy-results.sarif'

      - name: Upload Trivy scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v4
        if: always()
        with:
          sarif_file: 'trivy-results.sarif'
